broker/urls.py
from django.urls import path,re_path
from django.conf.urls import url
from . import views, api
from broker.views import student, instructor

urlpatterns = [
    path('', views.home, name='home'),
    path('student/', views.student_home, name='student_home'),
    path('apply/<int:id>/', views.application, name='apply_form'),
    path('apply/success/', views.application_success, name='application_success'),
    path('instructor/', views.instructor_home, name='instructor_home'),
    path('instructor/form/new/', views.instructor_create_form, name='create_form'),
    path('instructor/form/<int:id>/', views.instructor_form_detail, name='instructor_form_detail'),
    path('instructor/form/<int:pk>/delete', views.FormDeleteView.as_view(), name='instructor_form_delete'),
    path('instructor/res/<int:id>/', views.instructor_response_detail, name='instructor_response_detail'),
    path('api/change_response_state', api.change_response_state, name='change_response_state'),
    path('student/view_profile/', student.view_profile, name='view_profile'),
    path('student/update_profile/', student.update_profile.as_view(), name='update_profile'),
    path('instructor/view_profile/', instructor.view_profile, name="view_instructor_profile"),
    path('instructor/update_profile/', instructor.update_profile.as_view(), name="update_instructor_profile"),
    path('instructor/view_student_profile/<int:pk>', student.view_student_profile, name='view_student_profile'),
    path('student/view_instructor_profile/<int:pk>', instructor.view_instructor_profile, name='student_view_instructor_profile'),
    path('instrutor/create_course', instructor.CreateCourse.as_view(), name='create_course'),
    path('instrutor/view_course/<int:pk>', instructor.view_course, name='view_course'),
]

taremi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('account/', include('authentication.urls')),
    path('', include('broker.urls')),
    path('admin/', admin.site.urls),
]

broker/models.py
from django.db import models

from broker.constants import *
from authentication.models import Instructor, Student


class Course(models.Model):
    course_id = models.CharField("course ID", max_length=10)
    course_name = models.CharField("course Name", max_length=10)
    requirement = models.TextField("course Requirements")

    instructor = models.ForeignKey(Instructor, on_delete=models.CASCADE, related_name='courses')


class ApplicationForm(models.Model):
    # course_id = models.CharField("course_id", max_length=10)
    creator = models.ForeignKey(Instructor, on_delete=models.CASCADE, related_name='forms')
    release_date = models.DateField("release_date", auto_now=True)
    deadline = models.DateField("deadline")
    info = models.CharField("information", max_length=1000)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='forms')

    def get_responses(self):
        return self.responses


class Question(models.Model):
    class Meta:
        constraints = [models.UniqueConstraint(fields=['form', 'number'], name='unique_form_number')]

    form = models.ForeignKey(ApplicationForm, on_delete=models.CASCADE, related_name="questions")
    question = models.CharField("question", max_length=QUESTION_MAX_LENGTH, blank=False, null=False)
    number = models.IntegerField()
    type = models.CharField("type", max_length=255)

    def save(self, *args, **kwargs):
        self.type = self.__class__.__name__
        super().save(*args, **kwargs)

    def typed(self):
        if self.type:
            return self.__getattribute__(self.type.lower())
        else:
            return self

    def make_answer(self):
        raise NotImplementedError

    def __str__(self):
        return self.question



class ApplicationResponse(models.Model):
    owner = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='responses')
    date = models.DateField("date_submitted", auto_now=True)
    state = models.CharField(max_length=1, choices=APPLICATION_STATES)
    form = models.ForeignKey(ApplicationForm, on_delete=models.CASCADE, related_name='responses')

    def get_form(self):
        return self.form



class Answer(models.Model):
    response = models.ForeignKey(ApplicationResponse, on_delete=models.CASCADE, related_name='answers')
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    type = models.CharField("type", max_length=255)

    def save(self, *args, **kwargs):
        self.type = self.__class__.__name__
        super().save(*args, **kwargs)

    def typed(self):
        if self.type:
            return self.__getattribute__(self.type.lower())
        else:
            return self

class TextualQuestion(Question):
    def make_answer(self):
        t = TextualAnswer()
        t.question = self
        return t

class TextualAnswer(Answer):
    value = models.CharField('text_value', max_length=100, default="")
    def __str__(self):
        return self.value

class MultiChoiceQuestion(Question):
    def make_answer(self):
        t = MultiChoiceAnswer()
        t.question = self

class MultiChoiceAnswer(Answer):
    value = models.CharField("choice_value", max_length=CHOICE_MAX_LENGTH)

    def __str__(self):
        return self.value


class NumericalQuestion(Question):
    def make_answer(self):
        t = NumericalAnswer()
        t.question = self
        return t

class NumericalAnswer(Answer):
    value = models.IntegerField('int_value')

    def __str__(self):
        return str(self.value)

broker/forms.py
from .models import *
from django.db.models.query import EmptyQuerySet

class AnswerRenderer:
    def __init__(self, answer):
        self.answer = answer
        self.field_name = 'ans_%d' % self.answer.question.number

    def read_from_post(self, post_data):
        raise NotImplementedError()

    def render_editable(self):
        raise NotImplementedError()

    def render_fixed(self):
        raise NotImplementedError()


class TextualRenderer(AnswerRenderer):
    def read_from_post(self, post_data):
        self.answer.value = post_data[self.field_name]

    def render_fixed(self):
        return """<div style="background-color:#ff6699;"> Answer : %s</div><br/>""" % self.answer.value

    def render_editable(self):
        return """<input type="text" name="{name}" value="{value}"><br/>""".format(name=self.field_name, value=self.answer.value)

renderers = {TextualAnswer: TextualRenderer, NumericalAnswer: TextualRenderer}

def render_field(answer, editable):
    renderer = renderers[answer.__class__](answer)
    if editable:
        return renderer.render_editable()
    else:
        return renderer.render_fixed()

def render_form(form, response=None, editable=False):
    content = ""
    i = 1
    print(form.questions.order_by('number'))
    for q in form.questions.order_by('number'):
        if response is None:
            a = q.typed().make_answer()
            print('new response :: ', a.value)
        else:
            a = response.answers.get(question=q).typed()

        content += """
          <div class="field">
            <label style="background-color:#99ccff;"> Question {i} : {question}</label>
            {answer}
          </div>
        """.format(i=i, question=str(q), answer=render_field(a, editable))
        i += 1

    if editable:
        return """<form class="ui form" method="post">
            {csrf}
            <h1 class="ui header">{title}</h1>
            {content}
            <button class="ui button" type="submit">Submit</button>
            </form>""".format(title=form.info, content=content, csrf='{% csrf_token %}')
    else:
        return """<div class="ui form" method="post">
            <h1 class="ui header">Title: {title}</h1>
             <label>Student : {user}</label>
             <br/><br/>
            {content}
            </div>""".format(title=form.info, user=response.owner.get_full_name(), content=content)

def save_form(form, data, response):
    for q in form.questions.order_by('number'):
        a = response.answers.filter(question=q).first()
        if a is None:
            a = q.typed().make_answer()
            a.response = response
        else:
            a = a.typed()

        renderers[a.__class__](a).read_from_post(data)
        a.save()

broker/views/instructor.py
from datetime import datetime, timedelta

from django.db.models.query import EmptyQuerySet
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import DeleteView, UpdateView, CreateView
from ..models import *
from ..forms import render_form
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.shortcuts import redirect
from authentication.forms import InstructorForm
from authentication.decorators import active_required


@login_required()
def instructor_home(request):
    user = request.user
    forms = user.instructor.forms.all()
    return render(request, 'broker/instructor/home.html', context={'user':user, 'forms':forms })


@login_required()
def instructor_form_detail(request, id):
    form = ApplicationForm.objects.filter(id=id).first()

    if form is None:
        return redirect('instructor_home')

    #responses = [answer.response for answer in form.questions.first().answers.all()]
    responses = ApplicationResponse.objects.filter(form = form).distinct()
    return render(request, 'broker/instructor/form.html', context={'form':form , 'responses':responses})


@method_decorator([login_required], name='dispatch')
class FormDeleteView(DeleteView):
    model = ApplicationForm
    context_object_name = 'form'
    template_name = 'broker/instructor/form_delete.html'
    success_url = reverse_lazy('instructor_home')


    def get_queryset(self):
        return self.request.user.instructor.forms.all()


@login_required()
def instructor_response_detail(request, id):
    response = ApplicationResponse.objects.filter(id=id).first()
    if response is None:
        return redirect('instructor_home')

    form = response.get_form()
    html = render_form(form, response, False)

    return render(request, 'broker/instructor/response.html', context={'html':html, 'response':response})


@csrf_exempt
@login_required()
def instructor_create_form(request):
    if request.method == "GET":
        courses = Course.objects.filter(instructor=request.user.instructor)
        print(courses)
        return render(request, 'broker/instructor/form_creation.html', {'courses': courses})
    else:
        form = ApplicationForm(creator=request.user.instructor)
        form.release_date = datetime.now()
        form.deadline = request.POST["deadline"]
        form.course_id = request.POST["course"]
        form.info = request.POST["info"]
        form.save()
        for i in range(1, int(request.POST["length"]) + 1):
            if request.POST["q_%d_type" % i] == "textual":
                q = TextualQuestion(form=form, question=request.POST["q_%d_body" % i], number=i)
                q.save()

        return HttpResponse()

@login_required()
def view_profile(request):
    instructor = request.user.instructor
    return render(request, 'broker/instructor/view_instructor_profile.html', context={'instructor': instructor})

@method_decorator([login_required], name='dispatch')
class update_profile(UpdateView):
    model = Instructor
    form_class = InstructorForm
    template_name = 'broker/instructor/update_instructor_profile.html'

    def get_success_url(self):
        return reverse('instructor_home')

    def get_object(self, queryset=None):
        return self.request.user.instructor

@login_required()
def view_instructor_profile(request, pk):
    instructor = Instructor.objects.get(pk=pk)
    return render(request, 'broker/instructor/view_instructor_profile.html', context={'instructor': instructor})

@method_decorator([login_required], name='dispatch')
class CreateCourse(CreateView):
    model = Course
    fields = ('course_id', 'course_name', 'requirement', )
    template_name = 'broker/instructor/course_form.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        print(self.object)
        self.object.instructor = self.request.user.instructor
        self.object.save()
        print(self.object)

        return redirect('home')

@login_required()
@active_required()
def view_course(request, pk):
    course = Course.objects.get(pk=pk)
    return render(request, 'broker/instructor/view_course.html', context={'course': course})

broker/views/student.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.template import Template
from ..forms import render_form, save_form
from django.views.generic import UpdateView
from django.utils.decorators import method_decorator
from authentication.forms import StudentForm
from django.urls import reverse



from broker.models import *
from authentication.decorators import active_required

@login_required()
@active_required()
def student_home(request):
    student = request.user.student
    forms = ApplicationForm.objects.exclude(responses__owner=student)
    responses = student.responses.all()

    return render(request, 'broker/student/home.html', context={'user':request.user, 'forms':forms, 'responses': responses})

@login_required()
@active_required()
def application(request, id):
    form = ApplicationForm.objects.get(id=id)

    if request.method == "GET":
        form_template = Template(render_form(form, editable=True))
        form_html = form_template.render(RequestContext(request))

        return render(request, 'broker/student/application.html', context={'form': form_html})
    else:
        response = ApplicationResponse(owner=request.user.student, state = 'p', form=form)
        response.save()
        save_form(form, request.POST, response)

        return redirect('application_success')

def application_success(request):
    return render(request, 'broker/student/success.html', {'message' : 'Your Application Successfully Submited.'})


@login_required()
@active_required()
def view_profile(request):
    student = request.user.student
    return render(request, 'broker/student/view_student_profile.html', context={'student': student})

@method_decorator([login_required, active_required], name='dispatch')
class update_profile(UpdateView):
    model = Student
    form_class = StudentForm
    template_name = 'broker/student/update_profile.html'

    def get_success_url(self):
        return reverse('student_home')

    def get_object(self, queryset=None):
        return self.request.user.student


@login_required()
@active_required()
def view_student_profile(request, pk):
    student = Student.objects.get(student_id=pk)
    return render(request, 'broker/student/view_student_profile.html', context={'student': student})

broker/templates/broker/student/application.html
{% extends "broker/base.html"%}
{% block content %}
<div class="ui main text container" style="padding-left: -10em; ">
  <div class="ui raised segment">
    {{ form|safe }}
  </div>
</div>
{% endblock %}

broker/templates/broker/student/home.html
{% extends "broker/base.html"%}
{% load static %}

{% block content %}
  <div class="ui main text container" style="padding-left: -10em; ">
  <a class="fluid ui inverted secondary button" href="{% url 'view_profile' %}">View My Profile</a>
  <br>
  <a class="fluid ui inverted secondary button" href="{% url 'update_profile' %}">Update My Profile</a>
    <h1 class="ui header">List of Available Applications</h1>
    {% for form in forms %}
      <div class="ui raised segment">
          <div class="ui equal width grid">
            <div class="column middle aligned center aligned">
               <p><a href="{% url 'view_course' pk=form.course.pk %}">{{ form.course.course_name }}</a></p>
            </div>

            <div class="column middle aligned center aligned">

                <a class="ui labeled icon tiny button" tabindex="0" href="{% url 'student_view_instructor_profile' pk=form.creator.pk %}">
                    <i class="user icon"></i>
                        {{ form.creator.get_full_name }}

                </a>
            </div>

            <div class="column middle aligned center aligned">
                <div class="ui label">
                  Deadline
                  <div class="detail">{{ form.deadline|date:"M d" }}</div>
                </div>
            </div>

            <div class="column middle aligned center aligned">
                <a class="ui animated grey button" tabindex="0" href="{% url 'apply_form' id=form.id %}">
                  <div class="visible content">Apply</div>
                  <div class="hidden content">
                    <i class="right arrow icon"></i>
                  </div>
              </a>
            </div>

          </div>
      </div>
    {% endfor %}
    <h1 class="ui header">List of Ongoing Applications</h1>
    {% for resp in responses %}
      <div class="ui raised segment">
          <div class="ui equal width grid">

              <div class="column middle aligned center aligned">
                  <p>{{ resp.get_form.course_id }}</p>
              </div>

              <div class="column middle aligned center aligned">
                  <div class="ui label">
                    Instructor
                    <div class="detail">{{ resp.get_form.creator.get_full_name }}</div>
                  </div>
              </div>

              <div class="column middle aligned center aligned">
                  <div class="ui label {% if resp.state == 'a' %}green{% elif resp.state == 'd' %}red{% endif %}">
                    {{ resp.get_state_display }}
                  </div>
              </div>

          </div>
      </div>
    {% endfor %}

  </div>
{% endblock %}

broker/templates/broker/student/success.html
{% extends "broker/base.html"%}

{% block head %}
{{ block.super }}
<style>
  body > .grid {
    height: 100%;
  }
  .column {
    max-width: 450px;
  }
</style>
{% endblock %}

{% block content %}
    <div class="ui middle aligned center aligned grid">
      <div class="column">
              <div class="ui message success">{{ message|safe }}</div>
      </div>
    </div>

    <script type="text/javascript">
    setTimeout(function() {
        window.location.href = "{% url 'home' %}"
        }, 2000);
    </script>
{% endblock %}

broker/templates/broker/student/update_profile.html
{% extends "broker/base.html"%}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="ui main text container" style="padding-left: -10em; ">
    <h1 class="ui header">Update Profile</h1>

      <div class="ui raised segment">
          <div class="ui equal width grid">
            <div class="column middle aligned center aligned">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {{ form|crispy }}
                    <br>
                    <button class="ui primary button" type="submit">Save Changes</button>
                    <a class="ui button" href="{% url 'student_home' %}">Back</a>
                </form>
            </div>
          </div>
      </div>


  </div>
{% endblock %}

broker/templates/broker/student/view_student_profile.html
{% extends "broker/base.html"%}
{% load static %}

{% block content %}
  <div class="ui main text container" style="padding-left: -10em; ">
    <h1 class="ui header">Student Profile</h1>

      <div class="ui raised segment">
          <div class="ui equal width grid">
            <div class="column middle aligned center aligned">
                <p>Name: </p>
            </div>

            <div class="column middle aligned center aligned">
                <p>{{ student.get_full_name }}</p>
            </div>

          </div>
      </div>
      <div class="ui raised segment">
          <div class="ui equal width grid">
            <div class="column middle aligned center aligned">
                <p>Entrance Year: </p>
            </div>

            <div class="column middle aligned center aligned">
                <p>{{ student.get_entrance_year }}</p>
            </div>

          </div>
      </div>
      <div class="ui raised segment">
          <div class="ui equal width grid">
            <div class="column middle aligned center aligned">
                <p>Major: </p>
            </div>

            <div class="column middle aligned center aligned">
                <p>{{ student.get_major }}</p>
            </div>

          </div>
      </div>

        <div class="ui form">
            <div class="field">
                <div class="ui top attached label">About Me</div>
                <textarea disabled>{{ student.get_description }}</textarea>
            </div>
        </div>


  </div>
{% endblock %}